# Generated by Django 3.2.7 on 2021-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlideShow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='0', max_length=200, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default='0', max_length=200, verbose_name='title'),
        ),
    ]
